### ISSUE TITLE
How many nRF24 radio

### ISSUE THREAD

**Issue by roboticboyer** [dparson55/NRFLite#10]
Which is the max number of Radio_IDs I can use?
My understanding is that nRF24 has a data pipe so each RX can receive data from 6 different TXs
[see this block diagram](https://4.bp.blogspot.com/-FDWTGC5sKCc/VmLl1ypuy5I/AAAAAAAAAk8/OQqlJmMJi0I/s640/ExampleOfTransmission.jpg)
if confirmed,could you add an example
thank you

**Comment by dparson55** [comment]
This library only supports 1 receiving address.  It was an intentional decision to keep the library as easy to use as possible.  Since NRFLite supports sending and receiving dynamically sized packets with or without dynamically sized ACK packets, I didn't see much benefit to implementing all the different receiving addresses.  If you just need to know which transmitter sent a packet, you can see in the examples how I include a FromRadioId field in each data packet.  That seemed like an easier thing to do (and understand for users) than adding support for all the receiving addresses.

**Comment by adamzxtan** [comment]
Hi @dparson55, I just started looking at your library and I'm looking to build a sensor network with 1 master and 6 slave devices, doing two way communication. So based on the examples, I think there will be no issue for me to have like 6 slaves and 1 master doing two way communication? All I have to do is assign different RadioID for the slave devices right? (ex. RadioID 1 to 6)

**Comment by dparson55** [comment]
Yes that is correct, you just need to make sure each radio is assigned a different id.  If you watch the 2-pin operation video tutorial, about half way through I show the sensor example sketches which might help get you with your project.  Good luck!

**Comment by adamzxtan** [comment]
Thanks @dparson55. Will check out on your second video
