### ISSUE TITLE
 Error in ACK

### ISSUE THREAD

**Issue by lucasmaziero** [dparson55/NRFLite#15]
Hello, because even if I can not send the package I get the success message, only after sending four messages that I receive the failure message .. I believe that the failure message should already be on the first unsuccessful sending.. It seems like ACK error.

I am using the examples:
Basic_TX.ino and Basic_RX.ino

**Comment by dparson55** [comment]
Make sure Basic_RX.ino is actually running on the Arduino acting as a receiver.  Maybe print out the current millis() once per second on the receiver to ensure it is running.

What you have described is a situation where the transmitter is successfully sending packets but they are not being read from the receiver.  The nRF24L01+ module is able to store up to 3 packets in its RX FIFO buffer.  You must read them before more can be received.  If the packets are not read on the receiver, when the 4th packet is sent it will fail since the buffer on the receiving radio is full.

Here is a view of what is happening:
-TX radio sends packet 1, RX radio receives packet 1 and sends ACK.  RX FIFO buffer contains 1 packet.
-TX radio sends packet 2, RX radio receives packet 2 and sends ACK.  RX FIFO buffer contains 2 packets.
-TX radio sends packet 3, RX radio receives packet 3 and sends ACK.  RX FIFO buffer contains 3 packets.
-TX radio sends packet 4, RX radio cannot receive the packet because its RX FIFO buffer is full.

**Comment by lucasmaziero** [comment]
I would like to receive the unsuccessful submit error in "Basic_TX.ino" already in the first message that hears a send failure, is it possible?

**Comment by dparson55** [comment]
I am sure we can figure out a way to do what you need but you will probably need to explain in more detail what you are trying to do.

It is important to understand that what you said is already happening:  the first "send failure" is when packet 4 is sent because **packets 1, 2, and 3 have been successfully acknowledged by the receiving radio**.  It is only the failure of the Arduino on the receiving side to read the data that is currently stored inside the receiving radio.  The Arduino on the receiving side has called **radio.init** so it configured the radio to listen for packets, however, it is not doing its job of reading the data when the radio receives packets.  Hopefully that makes sense.

Maybe what you need is to prevent the receiving radio from receiving packets until you are ready to read them.  There are many ways to do this and here are 2 possibilities:
- Do not call **radio.init** on the receiving radio until you are ready to continually monitor the radio for packets.
- Call **radio.init** and then **radio.powerDown** on the receiving radio to turn off the radio and put it into a low power state.  It will stop listening for packets and only consume 900 nano-amps.  Calling **radio.hasData** will turn the radio back on.

**Comment by lucasmaziero** [comment]
This was the way I found that everything works fine and is sent 3 times with **for (uint8_t i = 0; i <3; i ++) _radio.send (DESTINATION_RADIO_ID, & _radioData, sizeof (_radioData))** and once again waiting for the I am not aware of the first 3 packets getting the 4 pack, I would like some suggestion of how this can be implemented in a better way .. Thanks

My code TX:
```c++
#include <SPI.h>
#include <NRFLite.h>
#include <SimpleThread.h> //https://github.com/lucasmaziero/SimpleThread

const static uint8_t RADIO_ID = 1;             // Our radio's id.
const static uint8_t DESTINATION_RADIO_ID = 0; // Id of the radio we will transmit to.
const static uint8_t PIN_RADIO_CE = 9;
const static uint8_t PIN_RADIO_CSN = 10;

uint32_t time = 0;

struct RadioPacket // Any packet up to 32 bytes can be sent.
{
  uint8_t FromRadioId;
  uint32_t OnTimeMillis;
  uint32_t FailedTxCount;
};

NRFLite _radio;
RadioPacket _radioData;

SimpleThread sendTime(5000);

void setup()
{
  Serial.begin(115200);

  if (!_radio.init(RADIO_ID, PIN_RADIO_CE, PIN_RADIO_CSN, NRFLite::BITRATE250KBPS))
  {
    Serial.println("Cannot communicate with radio");
    while (1); // Wait here forever.
  }

  _radioData.FromRadioId = RADIO_ID;
}

void loop()
{
  if (sendTime.check())
  {
    _radioData.OnTimeMillis = millis();

    Serial.print("Sending ");
    Serial.print(_radioData.OnTimeMillis);
    Serial.print(" ms");

    time = millis();
    for (uint8_t i = 0; i < 3; i++) _radio.send(DESTINATION_RADIO_ID, &_radioData, sizeof(_radioData));
    if (_radio.send(DESTINATION_RADIO_ID, &_radioData, sizeof(_radioData))) // Note how '&' must be placed in front of the variable name.
    {
      Serial.println("...Success");
    }
    else
    {
      Serial.println("...Failed");
      _radioData.FailedTxCount++;
    }

    Serial.print("Time: ");
    Serial.print(millis() - time);
    Serial.println(" ms");
  }
}
```
My code  RX:
```c++
#include <SPI.h>
#include <NRFLite.h>

const static uint8_t RADIO_ID = 0;       // Our radio's id.  The transmitter will send to this id.
const static uint8_t PIN_RADIO_CE = 9;
const static uint8_t PIN_RADIO_CSN = 10;

uint8_t i = 0;

struct RadioPacket // Any packet up to 32 bytes can be sent.
{
  uint8_t FromRadioId;
  uint32_t OnTimeMillis;
  uint32_t FailedTxCount;
};

NRFLite _radio;
RadioPacket _radioData;

void setup()
{
  Serial.begin(115200);

  if (!_radio.init(RADIO_ID, PIN_RADIO_CE, PIN_RADIO_CSN, NRFLite::BITRATE250KBPS))
  {
    Serial.println("Cannot communicate with radio");
    while (1); // Wait here forever.
  }
}

void loop()
{
  while (_radio.hasData())
  {
    _radio.readData(&_radioData); // Note how '&' must be placed in front of the variable name.

    if (dataIgnore())
    {
      String msg = "Radio ";
      msg += _radioData.FromRadioId;
      msg += ", ";
      msg += _radioData.OnTimeMillis;
      msg += " ms, ";
      msg += _radioData.FailedTxCount;
      msg += " Failed TX";

      Serial.println(msg);
    }
  }
}

bool dataIgnore()
{
  if (i++ >= 3)
  {
    i = 0;
    return true;
  }
  return false;
}
```

**Comment by dparson55** [comment]
I still do not understand the problem that you are experiencing.  The TX Arduino will fail on packet 1 if it does not receive an ACK from the RX Arduino:  there is no reason to send 4 packets nor have the receiver ignore 3 of the 4 packets.

Maybe during your testing you are holding down the RESET button on the RX Arduino in order to verify the TX Arduino fails to receive an ACK, but this can be a problem.  The nRF24L01 operates independent of the Arduino's microcontroller and will still be able to receive packets if it has been initialized with **radio.init**.  Holding the RESET button on the Arduino stops its microcontroller from running but it does not stop the nRF24L01.  Here are two examples to help explain:

*Scenerio 1 (RX Arduino and nRF24L01 are powered off)*

- Program Basic_TX.ino and Basic_RX.ino into your 2 Arduinos.
- Provide power to the TX Arduino and TX nRF24L01.
- Provide power to the RX Arduino and RX nRF24L01.
- After 1 packet is successfully sent, unplug the power from the RX Arduino and RX nRF24L01.
- When packet 2 is sent it will fail, when packet 3 is sent it will fail, etc.  It is failing because the TX Arduino is not receiving ACKs from the RX nRF24L01.

*Scenerio 2 (RX Arduino and nRF24L01 are powered on but the RX Arduino's **RESET** button is held down)*

- Program Basic_TX.ino and Basic_RX.ino into your 2 Arduinos.
- Provide power to the TX Arduino and TX nRF24L01.
- Provide power to the RX Arduino and RX nRF24L01.
- After 1 packet is successfully sent, press and hold the RESET button on the RX Arduino.
- The TX Arduino will successfully send 3 more packets because the RX nRF24L01 has been initialized and is receiving power.  The RESET button on the RX Arduino does not affect the RX nRF24L01 that it is connected to.  Packets 2, 3, and 4 will be successful and packet 5 will fail because the RX nRF24L01 has a buffer that can hold 3 packets, so on the 5th packet it will be full and the RX nRF24L01 will not send an ACK because it cannot receive any more packets.

Hopefully this is the problem you are seeing and it is just a side-effect of how you are performing tests.  The key to understand:  the TX Arduino will only show a successful transmission if it receives an ACK from the RX nRF24L01.  So turn off the power to the RX Arduino and RX nRF24L01 in order to see transmission failures on the TX Arduino.

**Comment by lucasmaziero** [comment]
Actually I'm pressing the Arduino reset in my tests, now when I take the power out of the RX the TX gets the ACK error as expected, now everything works 100%. Thank you for your help.

**Comment by dparson55** [comment]
Good to hear!
