### ISSUE TITLE
RX Example on ESP8266

### ISSUE THREAD

**Issue by 4uchip** [dparson55/NRFLite#31]
I copy and paste the code but it's not working properly, its send me:

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v8b899c12
~ld

I have read that could be a power issue but I connect the NRF24 to external power and give the same issue even when it is not connected, I think it could bee an SPI library issue. I am using NODEMUC 1.0v

**Comment by dparson55** [comment]
Sorry I won't be able to help since I don't have one of those boards.  But it looks like this is a very common error and is heavily discussed here https://github.com/esp8266/Arduino/issues/1809  Maybe you can post a more detailed question there.

Since it's not a NRFLite library issue, I'm going to close this.
