### ISSUE TITLE
Compatibility with samd based and other boards

### ISSUE THREAD

**Issue by mabstl1997** [dparson55/NRFLite#50]
Hello,
Thanks, developers, for the library.
I had a code that was running perfectly on an Arduino Nano clone with hardware SPI.
When trying to transfer it to an Arduino MKRZero (atsamd21 based board) with arduino native SPI, the compiler yelled:
... NRFLite\src/NRFLite.h:77:60: error: '_BV' was not declared in this scope
I have added:
#ifndef _BV
#define _BV(bit) (1 << (bit))
#endif
at the top of NRFLite.h and it solved the problem. May be there is more elegant way to solve this.
The sketch compiles with a warning that the library may be incompatible, but when uploaded it works as expected.
Could you update the library?

**Comment by dparson55** [comment]
Thanks for the tip, I updated the library and version 2.4.3 has the change.  Also, I went ahead and removed the pessimistic architecture setting on the library which caused the warning.  Now the library will be optimistic and I think this will be safe since Arduino SPI has consistently been included by new architectures.
