### ISSUE TITLE
Nrf24l01 does not go to standby-II

### ISSUE THREAD

**Issue by Cerantror** [dparson55/NRFLite#62]
When not using as the receiver the nrf do not go to low power mode also known as standby-II. I wanto to do battery application so this is quite important to me. I am using Seeeduino xiao and separate CE CSN pins.

**Comment by dparson55** [comment]
Set CE low to place the receiving radio into the standby mode.  When you want to start listening for data again, set CE high.  Another option is to call `powerDown` to put the radio into Power Down mode and later `init` to place the radio back into RX mode.  Using powerDown and init will conserve more power but it takes more time to perform this mode transition.

Just for completeness:  Standby-I is used by primary receivers while Standby-II is used by primary transmitters.  NRFLite actually avoids the usage of Standby-II since the nRF24L01+ datasheet mentions it is not a recommended state.  To do this packets are loaded into the TX FIFO buffer and the CE pin is pulsed high then low to send the packet.  This prevents the radio from entering Standby-II since CE is never held high when the TX FIFO buffer is empty.

Good luck!
