### ISSUE TITLE
Teensy 4 support?

### ISSUE THREAD

**Issue by Digital1O1** [dparson55/NRFLite#67]
When I used both the basic TX/RX examples on a pair of Arduino Nanos I had lying around, the example worked fine.

But with a project I'm currently working on, the main work horse is a Teensy 4.

When I ran the same examples (With the Teensy transmitting the message), it didn't work.

I've doubled checked my wiring and pretty much everything else and I'm under the assumption that this library doesn't support the Teensy microcontroller?

**Comment by dparson55** [comment]
NRFLite simply uses the SPI library (see https://github.com/dparson55/NRFLite/blob/master/src/NRFLite.cpp#L580) provided by the Teensy's Arduino core so I'm sure it will work.  There's a thread with some possible troubleshooting steps here:  https://forum.pjrc.com/threads/57507-SPI-on-Teensy-4

If you end up needing to call SPI.begin rather than having NRFLite do it, an example is shown here: https://github.com/dparson55/NRFLite/blob/master/examples/Basic_RX_ESP32/Basic_RX_ESP32.ino#L48
