### ISSUE TITLE
Basic_RX example reboots after some time

### ISSUE THREAD

**Issue by mvoss96** [dparson55/NRFLite#70]
Hi, i would like to use your library to control my robot car. 
Im currently testing your Basic_RX example but i have encountered a problem:
The transmission initially works, but after some random time the receiver always reboots.  
I added a  while(!Serial.available() ){ } in the setup so it is immediately obvious when it happens. 
I have tried two different nrf24l01 and two different arduino nanos, but i get the same behaviour every time. 

my modified RX example is below:
```

#include <servo.h>

  Demonstrates simple RX and TX operation.
  Any of the Basic_TX examples can be used as a transmitter.
  Please read through 'NRFLite.h' for a description of all the methods available in the library.

  Radio    Arduino
  CE    -> 9
  CSN   -> 10 (Hardware SPI SS)
  MOSI  -> 11 (Hardware SPI MOSI)
  MISO  -> 12 (Hardware SPI MISO)
  SCK   -> 13 (Hardware SPI SCK)
  IRQ   -> No connection
  VCC   -> No more than 3.6 volts
  GND   -> GND

*/

#include <SPI.h>
#include <NRFLite.h>

const static uint8_t RADIO_ID = 0;       // Our radio's id.  The transmitter will send to this id.
const static uint8_t PIN_RADIO_CE = 9;
const static uint8_t PIN_RADIO_CSN = 10;

struct RadioPacket // Any packet up to 32 bytes can be sent.
{
  uint8_t FromRadioId;
  uint32_t OnTimeMillis;
  uint32_t FailedTxCount;
};

NRFLite _radio;
RadioPacket _radioData;

Servo servo;

void setup()
{
  Serial.begin(115200);
  Serial.println("\n\n----------------START--------------\n\n");
  while(!Serial.available() ){ }
  servo.attach(2);

  // By default, 'init' configures the radio to use a 2MBPS bitrate on channel 100 (channels 0-125 are valid).
  // Both the RX and TX radios must have the same bitrate and channel to communicate with each other.
  // You can run the 'ChannelScanner' example to help select the best channel for your environment.
  // You can assign a different bitrate and channel as shown below.
  //   _radio.init(RADIO_ID, PIN_RADIO_CE, PIN_RADIO_CSN, NRFLite::BITRATE2MBPS, 100) // THE DEFAULT
  //   _radio.init(RADIO_ID, PIN_RADIO_CE, PIN_RADIO_CSN, NRFLite::BITRATE1MBPS, 75)
  //   _radio.init(RADIO_ID, PIN_RADIO_CE, PIN_RADIO_CSN, NRFLite::BITRATE250KBPS, 0)

  if (!_radio.init(RADIO_ID, PIN_RADIO_CE, PIN_RADIO_CSN, NRFLite::BITRATE2MBPS, 105))
  {
    Serial.println("Cannot communicate with radio");
    while (1); // Wait here forever.
  }
}

void loop()
{
  while (_radio.hasData())
  {
    _radio.readData(&_radioData); // Note how '&' must be placed in front of the variable name.

    String msg = "Radio ";
    msg += _radioData.FromRadioId;
    msg += ", ";
    msg += _radioData.OnTimeMillis;
    msg += " ms, ";
    msg += _radioData.FailedTxCount;
    msg += " Failed TX";

    Serial.println(msg);
  }
}`
```

Any Idea why that might happen?

**Comment by dparson55** [comment]
It might be a power issue, how did you initially realize the Arduino was being reset?  If you unplug the servo on pin 2, does the reset still occur?

The microcontroller used in the Arduino has a brown out detector set to 2.7V by default, and if a servo moves and causes the 5V powering the Arduino to drop below 2.7V, this brown out detector will see the voltage drop and reset the microcontroller.  It does this because when the voltage is this low, the microcontroller itself can malfunction and not be able to execute instructions correctly, or its peripherals like timers, EEPROM, ADC can malfunction.

I did a quick search on resets due to servos and it looks like a common problem.  This document has a couple of oscilloscope pictures that show an example of the voltage drop that can occur.  It shows how adding a large capacitor can help solve the problem.
http://www2.latech.edu/~kcorbett/LWTL/ENGT120/notes/08_fixing_resetting_robot.pdf

If a capacitor doesn't help, you can try powering the Arduino and radio with one set of batteries and power the servos with a completely different set.  You would just need to connect the grounds between the 2 sets of batteries together.

**Comment by mvoss96** [comment]
Thanks for your help, this was probably it.
I added a 4.7uF and a 0.1uF capacitor to the nrf module  and a dedicated power supply for the servo. Now the connection stays stable.

**Comment by dparson55** [comment]
Great news, good luck with your project!

**Comment by mvoss96** [comment]
@dparson55 
Thanks again for your help:
I have another question: 
I'm trying to control both a servo and and Esc from an Arduino nano who gets his commands from another Arduino nano using nrf24l01 radios.
I get the communication working perfectly now, however their seems to be some kind of interference between the nrflite and the servo libray, because during receiving of messages the servo sometimes buzzes (and the esc drives the motor a little) I'm guessing that something in the nrflite library blocks the timer1 that is used by the servo library to generate the servo signals. 

Could that be the case?
And if yes is there any way to fix this behaviour so that the servo signal stays stable even while receiving messages?

**Comment by dparson55** [comment]
@mvoss96
I moved the second question to issue #71 and put some options there that you can try.
