### ISSUE TITLE
RP2040 support

### ISSUE THREAD

**Issue by sweshn** [dparson55/NRFLite#74]
Today I use NRFlite for a project with 4 nodes  with Arduino Mega that have worked fine for long period now.

I have tried to use PR2040 instead. I have changed definition for SPI pins still no sucess.

Regards
Staffan

**Comment by dparson55** [comment]
What pin numbers did you try that did not work?

I looked around and discovered you can set your own SPI pins as described here https://arduino-pico.readthedocs.io/en/latest/spi.html  Maybe doing that will help.

Also during the search it seems there are a lot of pins labeled for SPI (https://forums.raspberrypi.com/viewtopic.php?t=320933) so you might just have to experiment since it doesn't look straightforward.  I found this pinout that shows all the possibilities when it comes to SPI:

![image](https://user-images.githubusercontent.com/19499747/149639266-7c721356-6fd8-4d5a-a564-f1de3d756366.png)

From this documentation (https://docs.arduino.cc/tutorials/nano-rp2040-connect/rp2040-01-technical-reference) here are the pins that I would initially try.

![image](https://user-images.githubusercontent.com/19499747/149639513-f9a6b442-b5b1-42bc-addf-5cacdf6c527c.png)

**Comment by dparson55** [comment]
@sweshn Any luck?

**Comment by dparson55** [comment]
Closing due to lack of response.

**Comment by sweshn** [comment]
Sorry for bad response !! I have problem with uploading sketches to RP2040 . Will solve that and after that continue with NRF lite.
