### ISSUE TITLE
SPI speed

### ISSUE THREAD

**Issue by Sinamajidi** [dparson55/NRFLite#89]
@dparson55 

Hello there,
The library is working well for me, but I want to mention a limitation of it to be solved.

The SPI speed is hard coded to 4MHz. However, the module can work with 10MHz (please check it in its datasheet. This was a quote from my friend that I just told you).

Also, it seems that many options of it are all enabled, and the state of those options can't be modified by the program, so it's   better to add some functions... to increase accessibility to the states and hardware options like changing power modes, Tx modes,... .

**Comment by dparson55** [comment]
> The SPI speed is hard coded to 4MHz.

The speed is set to 4MHz for 2 reasons:

1. Nordic lists 5 different resistance and capacitance loads on the SPI pins (tables 22-27 in the 1.0 datasheet) where table 22 shows the resistance and capacitance loads that result in a speed of 10MHz, while table 27 (shown below) lists a combination that results in a 4MHz speed. Since I want to give NRFLite the best possible chance of working using breadboard wiring, I chose to use the more conservative 4MHz speed. I've had issues using breadboard wiring for 8MHz SPI and considered using something slower than 4MHz, but so far 4MHz has proven to be reliable. And if the microcontroller is too slow to support 4MHz, it will just run as fast as it can, the hard-coded 4MHz speed will just be ignored.

![image](https://github.com/user-attachments/assets/ab9d98e5-2bdd-49cd-ad32-8e71f194f263)

2. The 4MHz SPI clock (which transfers data at 4Mbps) is still 2x the speed of the theoretical 2Mbps over-air capability of the nRF24L01. The NRFLite library itself is not very efficient when it comes to communicating with the nRF24L01 due to the design goals of the library, but it still can achieve a real-world 400Kbps over-air transfer rate with a 16MHz microcontroller under its fastest conditions (data rate set to 2Mbps, using the IRQ and separate CE and CSN pins, sending 32 byte packets, and no acknowledgment packets). A faster microcontroller like a 240MHz ESP32 would perform even better but if this speed is too slow for a particular application, then this library might not be a good fit. NRFLite has a lot of safety built into it behind the scenes to increase compatibility and ease of use, and the downside is the library is slower than it could be.

![image](https://github.com/user-attachments/assets/4273a27b-42bb-4d1a-a299-ec343f4570e4)

One additional thought, if the user is more of a power user and really wants to experiment with faster SPI, it's just a [1 line change](https://github.com/dparson55/NRFLite/blob/master/src/NRFLite.h#L80). So they can change the 4000000 to 10000000 and see if their wiring is compatible and perform testing to see if there is a significant real-world benefit.

> the module can work with 10MHz (please check it in its datasheet. This was a quote from my friend that I just told you).

Your friend is correct but do not open an issue asking a library author to check a datasheet, this is incredibly inconsiderate of their time. You yourself should look up the setting in question and provide it as a reference in the issue.

> It seems that many options of it are all enabled, and the state of those options can't be modified by the program, so it's better to add some functions... to increase accessibility to the states and hardware options like changing power modes, Tx modes

Unfortunately this conflicts with the design goals of NRFLite. NRFLite's main purpose is to make using the nRF24L01 simple while using a short and easy to understand public interface. The "Lite" of NRFLite is short for "Lightweight", meaning it is a small library with a limited amount of complexity. If this library allowed users to control all aspects of the nRF24L01, they could put the radio into unexpected configurations and create more special cases that would need to be managed. For example, if a user instructs the nRF24L01 to send some data and then instructs the nRF24L01 to switch into RX mode, NRFLite will [wait for all the data to be sent](https://github.com/dparson55/NRFLite/blob/master/src/NRFLite.cpp#L190) before allowing the RX mode switch to occur. As another example, if the nRF24L01's receive buffer is full and the user tries to send data that requires an acknowledgement, NRFLite will [clear the receive buffer](https://github.com/dparson55/NRFLite/blob/master/src/NRFLite.cpp#L456) before sending the data. These are just 2 of the many special cases NRFLite accounts for in order to give users a good experience. So in order to limit the number of issues users might encounter and increase its ease of use, NRFLite is designed around a limited feature set with a limited number of public properties and functions. NRFLite sacrafices features and speed to achieve these goals, but the benefit is this library is more likely to work when others may not.

Please note that if you need more control over the radio than NRFLite provides, the RF24 library is a great option. Unlike NRFLite which focuses on simplicity, RF24 focuses on speed and features. So it might be harder to get working but once you do, it will allow you to use the full capability of the nRF24L01. There is also the Mirf library which takes the opposite approach and is extremely basic, so there are lots of options that you can choose from. Good luck with your project!

- [Mirf](https://github.com/mberntsen/arduino/tree/master/libraries/Mirf): limited features, low-complexity, primary header and code files ~400 lines, ~30 public functions and properties
- [NRFLite](https://github.com/dparson55/NRFLite): more features, medium-complexity, primary header and code files ~800 lines, ~20 public functions and properties
- [RF24](https://github.com/nRF24/RF24): all features, high-complexity, primary header and code files ~4400 lines, ~70 public functions and properties

**Comment by dparson55** [comment]
Closing due to lack of response.
